# Generated by Django 4.1 on 2022-09-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_remove_room_online_message_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
    ]
